script: Fix missing terminating character in compile.h Refer to: https://github.com/LineageOS/android_kernel_sony_sm8250/blob/lineage-21/scripts/mkcompile_h#L76 Add "-m1" for grep to fix the following issues without hardcode compiler name (crdroidandroid/android_kernel_xiaomi_thyme@24b147d): - Warnings and errors about missing terminating '"' character and unknown type name '__s8'   while compiling include/generated/compile.h
Before the fix, the error messages were as follows:
In file included from ../init/version.c:9:
./include/generated/compile.h:7:24: warning: missing terminating '"' character [-Winvalid-pp-token]
    7 | #define LINUX_COMPILER "Android (12328485, +pgo, +bolt, +lto, +mlgo, based on r530567) clang version 19.0.0 (https://android.googlesource.com/toolchain/llvm-project 97a699bf4812a18fb657c2779f5296a4ab2694d2)
      |                        ^
./include/generated/compile.h:8:1: error: unknown type name 'Found'
    8 | Found CUDA installation: /opt/cuda, version, GNU ld (Linaro_Binutils-2017.01) 2.24.0.20141017 Linaro 2014_11-3-git"
      | ^
./include/generated/compile.h:8:11: error: expected ';' after top level declarator
    8 | Found CUDA installation: /opt/cuda, version, GNU ld (Linaro_Binutils-2017.01) 2.24.0.20141017 Linaro 2014_11-3-git"
      |           ^
      |           ;
./include/generated/compile.h:8:115: warning: missing terminating '"' character [-Winvalid-pp-token]
    8 | Found CUDA installation: /opt/cuda, version, GNU ld (Linaro_Binutils-2017.01) 2.24.0.20141017 Linaro 2014_11-3-git"
      |                                                                                                                   ^
In file included from ../init/version.c:10:
In file included from ../include/linux/build-salt.h:4:
In file included from ../include/linux/elfnote.h:62:
In file included from ../include/uapi/linux/elf.h:5:
In file included from ../include/linux/types.h:6:
In file included from ../include/uapi/linux/types.h:5:
In file included from ./arch/arm64/include/generated/uapi/asm/types.h:1:
In file included from ../include/uapi/asm-generic/types.h:7:
../include/asm-generic/int-ll64.h:16:9: error: unknown type name '__s8'; did you mean '__u8'?
   16 | typedef __s8  s8;
      |         ^~~~
      |         __u8
../include/uapi/asm-generic/int-ll64.h:21:23: note: '__u8' declared here
   21 | typedef unsigned char __u8;
      |                       ^
../init/version.c:47:26: error: expected ';' after top level declarator
   47 |         LINUX_COMPILE_HOST ") (" LINUX_COMPILER ") " UTS_VERSION "\n";
      |                                 ^
      |                                 ;
../init/version.c:55:6: error: expected ';' after top level declarator
   55 |         " (" LINUX_COMPILER ") %s\n";
      |             ^
      |             ;
2 warnings and 5 errors generated.